# Generated by Django 5.0.7 on 2024-07-20 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0008_auto_20240716_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatEmotion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('response_text', models.CharField(blank=True, max_length=500, null=True)),
                ('emotion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'chat_emotions',
            },
        ),
    ]
